

init:
  seed: 42


data:
  train:
    name: 
    hq_img_path: 
    ann_path: 
    hq_prompt_path: 
    null_text_ratio: 

  val:
    eval_list: [realtext]

    realtext:
      lq_img_path: /mnt/dataset1/text_restoration/tair_published/real_text/LQ
      hq_img_path: /mnt/dataset1/text_restoration/tair_published/real_text/HQ
      ann_path: /mnt/dataset1/text_restoration/tair_published/real_text/realtext_ann.json
      # vlm_caption_path: result_vlm/orig_dit4sr/realtext/llava13b_prompt
      # vlm_caption_path: result_vlm/lq_caption/realtext/realtext_Englishques0/qwenvl_7b
      # vlm_caption_path: result_vlm/lq_caption/realtext/realtext_Englishques1/qwenvl_7b
      vlm_caption_path: result_vlm/lq_caption/realtext/realtext_Englishques2/qwenvl_7b
      # vlm_caption_path: result_vlm/lq_caption/realtext/realtext_Englishques3/qwenvl_7b
      val_num_img: 847
      # val_img_id: []
      val_img_id: [Canon_001_HR_crop_1, Canon_21_x4_5_crop_0, Canon_24_x4_21_crop_0, Canon_30_x4_44_crop_0, Canon_31_x4_52_crop_0, Canon_32_x4_21_crop_0, Canon_32_x4_23_crop_0, Canon_33_x4_33_crop_0, Canon_37_x4_45_crop_0, Canon_41_x4_32_crop_0, Canon_41_x4_35_crop_0, DSC_0972_x4_13_crop_0, DSC_0984_x4_2_crop_0, DSC_0984_x4_6_crop_0, DSC_1023_x4_16_crop_0, DSC_1330_x4_4_crop_0, DSC_1342_x4_6_crop_0,  ]

    satext_lv1:
      lq_img_path: 
      hq_img_path: 
      ann_path: 
      vlm_captioner: 
      vlm_input_ques: 
      vlm_caption_path: 
      val_num_img: 
      val_img_id: []
  
    satext_lv2:
      lq_img_path: 
      hq_img_path: 
      ann_path: 
      vlm_captioner: 
      vlm_input_ques: 
      vlm_caption_path: 
      val_num_img: 
      val_img_id: []

    satext_lv3:
      lq_img_path: 
      hq_img_path: 
      ann_path: 
      vlm_captioner: 
      vlm_input_ques: 
      vlm_caption_path: 
      val_num_img: 
      val_img_id: []


    # text_cond_prompt: "null"
    # text_cond_prompt: "gt"
    text_cond_prompt: "pred_tsm"
    # text_cond_prompt: "pred_vlm"


    vlm:
      vlm_correction: True 
      model: qwenvl-7b
      vlm_apply_at_iter: [10]


    ocr:
      vis_ocr: True
      # vis_timestep: [-1] # visualize all timesteps
      vis_timestep: [0, 1, 2, 3, 4, 5, 10, 20, 30, 39]  # visualize selected time iter
    

    attn:
      vis_map: False

    eval_region: all


    added_prompt:
    negative_prompt: 
    # added_prompt: Cinematic, hyper sharpness, highly detailed, perfect without deformations, camera, hyper detailed photo - realistic maximum detail, 32k, Color Grading, ultra HD, extreme meticulous detailing, skin pore detailing.
    # negative_prompt: motion blur, noisy, dotted, bokeh, pointed, CG Style, 3D render, unreal engine, blurring, dirty, messy, worst quality, low quality, frames, watermark, signature, jpeg artifacts, deformed, lowres, chaotic
    save_prompts: True
    sample_times: 1
    guidance_scale: 1.0
    start_point: noise
    latent_tiled_size: 64
    latent_tiled_overlap: 24
    upscale: 4
    process_size: 512
    num_inference_steps: 40
    # choose from [adain, wavelet]
    align_method: adain


model:
  noise_scheduler:
    weighting_scheme: 
    logit_mean: 
    logit_std: 
    mode_scale: 
    precondition_outputs:
  dit:
    name: 
    resolution: 
    load_precomputed_caption: 
    use_gtprompt: 
    text_condition:
      caption_style: descriptive
  ts_module:
    name:  


ckpt:
  init_path:
    vae: preset/models/stable-diffusion-3.5-medium
    noise_scheduler: preset/models/stable-diffusion-3.5-medium
    tokenizer: preset/models/stable-diffusion-3.5-medium
    text_encoder: preset/models/stable-diffusion-3.5-medium
    dit: 
    ts_module: 
  resume_path:    
    dit: result_train/unit_ckpt/dit
    ts_module: result_train/unit_ckpt/tsm.pt


train:
  stage: stage2
  mixed_precision: 'fp16'
  model: ['transformer', 'ts_module']
  transformer:
    architecture: "dit4sr"
    ocr_branch_init: 
    lr: 
    finetune_layer_names: []
    feat_extract: hqlq_feat
    feat_extract_layer: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]
  ts_module:
    architecture: testr
    lr: 
    finetune_layer_names: []
  num_train_epochs: 
  batch_size:        
  num_workers: 
  gradient_accumulation_steps: 
  max_train_steps: 
  lr_scheduler: 
  lr_warmup_steps:
  lr_num_cycles: 
  lr_power: 
  max_grad_norm: 
  set_grads_to_none: 
  scale_lr: 
  use_8bit_adam: 
  ocr_loss_weight: 
val:
  val_every_step: 


save:
  output_dir: result_val/unit
  checkpointing_steps:


log:
  tracker: 
    report_to: wandb
    key: e32eed0c2509bf898b850b0065ab62345005fb73
    project_name: cvpr26_unit
    server: 20
    gpu: 7
    msg: "unit__vlm-ques2-qwenvl-7b-correct-10__cfg1"
  log_dir: logs
